In [1]:
import numpy as np
import pandas as pd

### Reading dataset

In [2]:
DATASET=pd.read_csv("dataset.csv")

### Explore Dataset

In [3]:
DATASET.head()

id  gender   age  hypertension  heart_disease ever_married  \
0  30669    Male   3.0             0              0           No   
1  30468    Male  58.0             1              0          Yes   
2  16523  Female   8.0             0              0           No   
3  56543  Female  70.0             0              0          Yes   
4  46136    Male  14.0             0              0           No   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0      children          Rural              95.12  18.0              NaN   
1       Private          Urban              87.96  39.2     never smoked   
2       Private          Urban             110.89  17.6              NaN   
3       Private          Rural              69.04  35.9  formerly smoked   
4  Never_worked          Rural             161.28  19.1              NaN   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
DATASET.tail()

id  gender   age  hypertension  heart_disease ever_married  \
43395  56196  Female  10.0             0              0           No   
43396   5450  Female  56.0             0              0          Yes   
43397  28375  Female  82.0             1              0          Yes   
43398  27973    Male  40.0             0              0          Yes   
43399  36271  Female  82.0             0              0          Yes   

      work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
43395  children          Urban              58.64  20.4     never smoked   
43396  Govt_job          Urban             213.61  55.4  formerly smoked   
43397   Private          Urban              91.94  28.9  formerly smoked   
43398   Private          Urban              99.16  33.2     never smoked   
43399   Private          Urban              79.48  20.6     never smoked   

       stroke  
43395       0  
43396       0  
43397       0  
43398       0  
43399       0

In [5]:
DATASET.shape

(43400, 12)

In [6]:
DATASET=DATASET.drop(columns=['id'])
DATASET

gender   age  hypertension  heart_disease ever_married     work_type  \
0        Male   3.0             0              0           No      children   
1        Male  58.0             1              0          Yes       Private   
2      Female   8.0             0              0           No       Private   
3      Female  70.0             0              0          Yes       Private   
4        Male  14.0             0              0           No  Never_worked   
...       ...   ...           ...            ...          ...           ...   
43395  Female  10.0             0              0           No      children   
43396  Female  56.0             0              0          Yes      Govt_job   
43397  Female  82.0             1              0          Yes       Private   
43398    Male  40.0             0              0          Yes       Private   
43399  Female  82.0             0              0          Yes       Private   

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0              Rural              95.12  18.0              NaN       0  
1              Urban              87.96  39.2     never smoked       0  
2              Urban             110.89  17.6              NaN       0  
3              Rural              69.04  35.9  formerly smoked       0  
4              Rural             161.28  19.1              NaN       0  
...              ...                ...   ...              ...     ...  
43395          Urban              58.64  20.4     never smoked       0  
43396          Urban             213.61  55.4  formerly smoked       0  
43397          Urban              91.94  28.9  formerly smoked       0  
43398          Urban              99.16  33.2     never smoked       0  
43399          Urban              79.48  20.6     never smoked       0  

[43400 rows x 11 columns]

In [7]:
DATASET['stroke'].value_counts()

0    42617
1      783
Name: stroke, dtype: int64

#### Identify input ,output

In [8]:
x=DATASET.iloc[:,:-1].values         #input
y=DATASET.iloc[:,-1].values          #output
pd.DataFrame(x)

0     1  2  3    4             5      6       7     8  \
0        Male   3.0  0  0   No      children  Rural   95.12  18.0   
1        Male  58.0  1  0  Yes       Private  Urban   87.96  39.2   
2      Female   8.0  0  0   No       Private  Urban  110.89  17.6   
3      Female  70.0  0  0  Yes       Private  Rural   69.04  35.9   
4        Male  14.0  0  0   No  Never_worked  Rural  161.28  19.1   
...       ...   ... .. ..  ...           ...    ...     ...   ...   
43395  Female  10.0  0  0   No      children  Urban   58.64  20.4   
43396  Female  56.0  0  0  Yes      Govt_job  Urban  213.61  55.4   
43397  Female  82.0  1  0  Yes       Private  Urban   91.94  28.9   
43398    Male  40.0  0  0  Yes       Private  Urban   99.16  33.2   
43399  Female  82.0  0  0  Yes       Private  Urban   79.48  20.6   

                     9  
0                  NaN  
1         never smoked  
2                  NaN  
3      formerly smoked  
4                  NaN  
...                ...  
43395     never smoked  
43396  formerly smoked  
43397  formerly smoked  
43398     never smoked  
43399     never smoked  

[43400 rows x 10 columns]

#### Data Cleaning

In [9]:
from sklearn.impute import SimpleImputer as si
imputer_bmi=si(missing_values=np.nan,strategy='mean')
x[:,8:9]=imputer_bmi.fit_transform(x[:,8:9])

imputer_smoking_status=si(missing_values=np.nan,strategy='most_frequent')
x[:,9:10]=imputer_smoking_status.fit_transform(x[:,9:10])
pd.DataFrame(x)

0     1  2  3    4             5      6       7     8  \
0        Male   3.0  0  0   No      children  Rural   95.12  18.0   
1        Male  58.0  1  0  Yes       Private  Urban   87.96  39.2   
2      Female   8.0  0  0   No       Private  Urban  110.89  17.6   
3      Female  70.0  0  0  Yes       Private  Rural   69.04  35.9   
4        Male  14.0  0  0   No  Never_worked  Rural  161.28  19.1   
...       ...   ... .. ..  ...           ...    ...     ...   ...   
43395  Female  10.0  0  0   No      children  Urban   58.64  20.4   
43396  Female  56.0  0  0  Yes      Govt_job  Urban  213.61  55.4   
43397  Female  82.0  1  0  Yes       Private  Urban   91.94  28.9   
43398    Male  40.0  0  0  Yes       Private  Urban   99.16  33.2   
43399  Female  82.0  0  0  Yes       Private  Urban   79.48  20.6   

                     9  
0         never smoked  
1         never smoked  
2         never smoked  
3      formerly smoked  
4         never smoked  
...                ...  
43395     never smoked  
43396  formerly smoked  
43397  formerly smoked  
43398     never smoked  
43399     never smoked  

[43400 rows x 10 columns]

#### Data Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,MinMaxScaler
lb=LabelEncoder()
x[:,0]=lb.fit_transform(x[:,0])
x[:,4]=lb.fit_transform(x[:,4])
x[:,6]=lb.fit_transform(x[:,6])

from sklearn.compose import ColumnTransformer
OneHotEncoder=ColumnTransformer([('encoder',OneHotEncoder(),[5,9])],remainder='passthrough')
x=OneHotEncoder.fit_transform(x)
pd.DataFrame(x)


0    1    2    3    4    5    6    7  8     9  10 11 12 13      14  \
0      0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1   3.0  0  0  0  0   95.12   
1      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  58.0  1  0  1  1   87.96   
2      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0   8.0  0  0  0  1  110.89   
3      0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  70.0  0  0  1  0   69.04   
4      0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1  14.0  0  0  0  0  161.28   
...    ...  ...  ...  ...  ...  ...  ...  ... ..   ... .. .. .. ..     ...   
43395  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0  10.0  0  0  0  1   58.64   
43396  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0  56.0  0  0  1  1  213.61   
43397  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  82.0  1  0  1  1   91.94   
43398  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  40.0  0  0  1  1   99.16   
43399  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0  82.0  0  0  1  1   79.48   

         15  
0      18.0  
1      39.2  
2      17.6  
3      35.9  
4      19.1  
...     ...  
43395  20.4  
43396  55.4  
43397  28.9  
43398  33.2  
43399  20.6  

[43400 rows x 16 columns]

#### Data Normalization

In [11]:
mms=MinMaxScaler()      # scaling 
x[:,9:]=mms.fit_transform(x[:,9:])
pd.DataFrame(x)

0    1    2    3    4    5    6    7  8         9    10   11   12  \
0      0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1  0.035645  0.0  0.0  0.0   
1      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  0.707031  1.0  0.0  1.0   
2      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0   0.09668  0.0  0.0  0.0   
3      0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  0.853516  0.0  0.0  1.0   
4      0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1  0.169922  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ... ..       ...  ...  ...  ...   
43395  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0  0.121094  0.0  0.0  0.0   
43396  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0  0.682617  0.0  0.0  1.0   
43397  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0       1.0  1.0  0.0  1.0   
43398  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  0.487305  0.0  0.0  1.0   
43399  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0       1.0  0.0  0.0  1.0   

        13        14        15  
0      0.0  0.169964  0.090286  
1      1.0  0.139631  0.332571  
2      1.0  0.236772  0.085714  
3      0.0  0.059479  0.294857  
4      0.0  0.450244  0.102857  
...    ...       ...       ...  
43395  1.0   0.01542  0.117714  
43396  1.0  0.671934  0.517714  
43397  1.0  0.156492  0.214857  
43398  1.0  0.187079     0.264  
43399  1.0  0.103707      0.12  

[43400 rows x 16 columns]

#### Data Spliting

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.7,random_state=5)

## Machine Learning Models

### 1_Random Forest , Grid search

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score , classification_report
rfc=RandomForestClassifier()

In [14]:
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [17]:
from sklearn.model_selection import GridSearchCV
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [200, 500]})

In [20]:
CV_rfc.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'max_features': 'auto',
 'n_estimators': 200}

In [21]:
rfc=RandomForestClassifier(criterion='gini',max_depth=4,max_features='auto',n_estimators=200)
rfc.fit(x_train, y_train)
y_pred=rfc.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.9801858536210737


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[12763     0]
 [  258     0]]




### 2_KNN Model

In [ ]:
from sklearn.neighbors import NearestCentroid
KNN=NearestCentroid()
KNN.fit(x_train, y_train)
y_pred=KNN.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.6647722909146763


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[8462 4301]
 [  64  194]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.66      0.79     12763
           1       0.04      0.75      0.08       258

    accuracy                           0.66     13021
   macro avg       0.52      0.71      0.44     13021
weighted avg       0.97      0.66      0.78     13021



### 3_Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
clss=LogisticRegression(random_state=0)
clss.fit(x_train,y_train)
y_pred=clss.predict(x_test)
print(accuracy_score(y_test,y_pred))


0.9801858536210737


In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,median_absolute_error
print ("Mean absolute Error",mean_absolute_error(y_test,y_pred))
print ("Mean squared Error",mean_squared_error(y_test,y_pred))
print ("Median absolute Error",median_absolute_error(y_test,y_pred))

Mean absolute Error 0.01981414637892635
Mean squared Error 0.01981414637892635
Median absolute Error 0.0


In [ ]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12763     0]
 [  258     0]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12763
           1       0.00      0.00      0.00       258

    accuracy                           0.98     13021
   macro avg       0.49      0.50      0.49     13021
weighted avg       0.96      0.98      0.97     13021



c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



### 4_Naive_bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes_model=MultinomialNB()
naive_bayes_model.fit(x_train, y_train)
y_pred=naive_bayes_model.predict(x_test)
print(accuracy_score(y_test, y_pred))


0.9801858536210737


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[12763     0]
 [  258     0]]


#### outliers

In [ ]:
# Z score = (Observation — Mean)/Standard Deviation
# z = (X — μ) / σ
# dataset_test= [11,10,12,14,12,15,14,13,15,102,12,14,17,19,107, 10,13,12,14,12,108,12,11,14,13,15,10,15,12,10,14,13,15,10]


In [ ]:
outliers=[]
def detect_outliers(data):
    
    threshold=2
    mean = np.mean(data)
    std =np.std(data)
    
    
    for i in data:
        z_score= (i - mean)/std 
        print(z_score)
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

In [18]:
#outlier_pt=detect_outliers(x[:,7])

In [19]:
#outlier_pt