In [1]:
import numpy as np
import pandas as pd

### Reading dataset

In [2]:
DATASET=pd.read_csv("dataset.csv")

### Explore Dataset

In [15]:
DATASET.head()

gender   age  hypertension  heart_disease ever_married     work_type  \
0    Male   3.0             0              0           No      children   
1    Male  58.0             1              0          Yes       Private   
2  Female   8.0             0              0           No       Private   
3  Female  70.0             0              0          Yes       Private   
4    Male  14.0             0              0           No  Never_worked   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Rural              95.12  18.0              NaN       0  
1          Urban              87.96  39.2     never smoked       0  
2          Urban             110.89  17.6              NaN       0  
3          Rural              69.04  35.9  formerly smoked       0  
4          Rural             161.28  19.1              NaN       0

In [16]:
DATASET.tail()

gender   age  hypertension  heart_disease ever_married work_type  \
43395  Female  10.0             0              0           No  children   
43396  Female  56.0             0              0          Yes  Govt_job   
43397  Female  82.0             1              0          Yes   Private   
43398    Male  40.0             0              0          Yes   Private   
43399  Female  82.0             0              0          Yes   Private   

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
43395          Urban              58.64  20.4     never smoked       0  
43396          Urban             213.61  55.4  formerly smoked       0  
43397          Urban              91.94  28.9  formerly smoked       0  
43398          Urban              99.16  33.2     never smoked       0  
43399          Urban              79.48  20.6     never smoked       0

In [17]:
DATASET.shape

(43400, 11)

In [3]:
DATASET=DATASET.drop(columns=['id'])
DATASET

gender   age  hypertension  heart_disease ever_married     work_type  \
0        Male   3.0             0              0           No      children   
1        Male  58.0             1              0          Yes       Private   
2      Female   8.0             0              0           No       Private   
3      Female  70.0             0              0          Yes       Private   
4        Male  14.0             0              0           No  Never_worked   
...       ...   ...           ...            ...          ...           ...   
43395  Female  10.0             0              0           No      children   
43396  Female  56.0             0              0          Yes      Govt_job   
43397  Female  82.0             1              0          Yes       Private   
43398    Male  40.0             0              0          Yes       Private   
43399  Female  82.0             0              0          Yes       Private   

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0              Rural              95.12  18.0              NaN       0  
1              Urban              87.96  39.2     never smoked       0  
2              Urban             110.89  17.6              NaN       0  
3              Rural              69.04  35.9  formerly smoked       0  
4              Rural             161.28  19.1              NaN       0  
...              ...                ...   ...              ...     ...  
43395          Urban              58.64  20.4     never smoked       0  
43396          Urban             213.61  55.4  formerly smoked       0  
43397          Urban              91.94  28.9  formerly smoked       0  
43398          Urban              99.16  33.2     never smoked       0  
43399          Urban              79.48  20.6     never smoked       0  

[43400 rows x 11 columns]

In [4]:
DATASET['stroke'].value_counts()

0    42617
1      783
Name: stroke, dtype: int64

#### Identify input ,output

In [5]:
x=DATASET.iloc[:,:-1].values         #input
y=DATASET.iloc[:,-1].values          #output
pd.DataFrame(x)

0     1  2  3    4             5      6       7     8  \
0        Male   3.0  0  0   No      children  Rural   95.12  18.0   
1        Male  58.0  1  0  Yes       Private  Urban   87.96  39.2   
2      Female   8.0  0  0   No       Private  Urban  110.89  17.6   
3      Female  70.0  0  0  Yes       Private  Rural   69.04  35.9   
4        Male  14.0  0  0   No  Never_worked  Rural  161.28  19.1   
...       ...   ... .. ..  ...           ...    ...     ...   ...   
43395  Female  10.0  0  0   No      children  Urban   58.64  20.4   
43396  Female  56.0  0  0  Yes      Govt_job  Urban  213.61  55.4   
43397  Female  82.0  1  0  Yes       Private  Urban   91.94  28.9   
43398    Male  40.0  0  0  Yes       Private  Urban   99.16  33.2   
43399  Female  82.0  0  0  Yes       Private  Urban   79.48  20.6   

                     9  
0                  NaN  
1         never smoked  
2                  NaN  
3      formerly smoked  
4                  NaN  
...                ...  
43395     never smoked  
43396  formerly smoked  
43397  formerly smoked  
43398     never smoked  
43399     never smoked  

[43400 rows x 10 columns]

#### Data Cleaning

In [6]:
from sklearn.impute import SimpleImputer as si
imputer_bmi=si(missing_values=np.nan,strategy='mean')
x[:,8:9]=imputer_bmi.fit_transform(x[:,8:9])

imputer_smoking_status=si(missing_values=np.nan,strategy='most_frequent')
x[:,9:10]=imputer_smoking_status.fit_transform(x[:,9:10])
pd.DataFrame(x)

0     1  2  3    4             5      6       7     8  \
0        Male   3.0  0  0   No      children  Rural   95.12  18.0   
1        Male  58.0  1  0  Yes       Private  Urban   87.96  39.2   
2      Female   8.0  0  0   No       Private  Urban  110.89  17.6   
3      Female  70.0  0  0  Yes       Private  Rural   69.04  35.9   
4        Male  14.0  0  0   No  Never_worked  Rural  161.28  19.1   
...       ...   ... .. ..  ...           ...    ...     ...   ...   
43395  Female  10.0  0  0   No      children  Urban   58.64  20.4   
43396  Female  56.0  0  0  Yes      Govt_job  Urban  213.61  55.4   
43397  Female  82.0  1  0  Yes       Private  Urban   91.94  28.9   
43398    Male  40.0  0  0  Yes       Private  Urban   99.16  33.2   
43399  Female  82.0  0  0  Yes       Private  Urban   79.48  20.6   

                     9  
0         never smoked  
1         never smoked  
2         never smoked  
3      formerly smoked  
4         never smoked  
...                ...  
43395     never smoked  
43396  formerly smoked  
43397  formerly smoked  
43398     never smoked  
43399     never smoked  

[43400 rows x 10 columns]

#### Data Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,MinMaxScaler
lb=LabelEncoder()
x[:,0]=lb.fit_transform(x[:,0])
x[:,4]=lb.fit_transform(x[:,4])
x[:,6]=lb.fit_transform(x[:,6])

from sklearn.compose import ColumnTransformer
OneHotEncoder=ColumnTransformer([('encoder',OneHotEncoder(),[5,9])],remainder='passthrough')
x=OneHotEncoder.fit_transform(x)
pd.DataFrame(x)


0    1    2    3    4    5    6    7  8     9  10 11 12 13      14  \
0      0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1   3.0  0  0  0  0   95.12   
1      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  58.0  1  0  1  1   87.96   
2      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0   8.0  0  0  0  1  110.89   
3      0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  70.0  0  0  1  0   69.04   
4      0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1  14.0  0  0  0  0  161.28   
...    ...  ...  ...  ...  ...  ...  ...  ... ..   ... .. .. .. ..     ...   
43395  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0  10.0  0  0  0  1   58.64   
43396  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0  56.0  0  0  1  1  213.61   
43397  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  82.0  1  0  1  1   91.94   
43398  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  40.0  0  0  1  1   99.16   
43399  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0  82.0  0  0  1  1   79.48   

         15  
0      18.0  
1      39.2  
2      17.6  
3      35.9  
4      19.1  
...     ...  
43395  20.4  
43396  55.4  
43397  28.9  
43398  33.2  
43399  20.6  

[43400 rows x 16 columns]

#### Data Normalization

In [8]:
mms=MinMaxScaler()      # scaling 
x[:,9:]=mms.fit_transform(x[:,9:])
pd.DataFrame(x)

0    1    2    3    4    5    6    7  8         9    10   11   12  \
0      0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1  0.035645  0.0  0.0  0.0   
1      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  0.707031  1.0  0.0  1.0   
2      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0   0.09668  0.0  0.0  0.0   
3      0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0  0.853516  0.0  0.0  1.0   
4      0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1  0.169922  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ... ..       ...  ...  ...  ...   
43395  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0  0.121094  0.0  0.0  0.0   
43396  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0  0.682617  0.0  0.0  1.0   
43397  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0       1.0  1.0  0.0  1.0   
43398  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1  0.487305  0.0  0.0  1.0   
43399  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0       1.0  0.0  0.0  1.0   

        13        14        15  
0      0.0  0.169964  0.090286  
1      1.0  0.139631  0.332571  
2      1.0  0.236772  0.085714  
3      0.0  0.059479  0.294857  
4      0.0  0.450244  0.102857  
...    ...       ...       ...  
43395  1.0   0.01542  0.117714  
43396  1.0  0.671934  0.517714  
43397  1.0  0.156492  0.214857  
43398  1.0  0.187079     0.264  
43399  1.0  0.103707      0.12  

[43400 rows x 16 columns]

#### Data Spliting

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.7,random_state=5)

## Machine Learning Models

### 1_Random Forest , Grid search

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score , classification_report
rfc=RandomForestClassifier()

In [85]:
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [87]:
from sklearn.model_selection import GridSearchCV
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [200, 500]})

In [88]:
CV_rfc.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'max_features': 'auto',
 'n_estimators': 200}

In [89]:
rfc=RandomForestClassifier(criterion='gini',max_depth=4,max_features='auto',n_estimators=200)
rfc.fit(x_train, y_train)
y_pred=rfc.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.9801858536210737


In [90]:
print(confusion_matrix(y_test, y_pred))

[[12763     0]
 [  258     0]]




### 2_KNN Model

In [79]:
from sklearn.neighbors import NearestCentroid
KNN=NearestCentroid()
KNN.fit(x_train, y_train)
y_pred=KNN.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.6647722909146763


In [80]:
print(confusion_matrix(y_test, y_pred))

[[8462 4301]
 [  64  194]]


In [81]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.66      0.79     12763
           1       0.04      0.75      0.08       258

    accuracy                           0.66     13021
   macro avg       0.52      0.71      0.44     13021
weighted avg       0.97      0.66      0.78     13021



### 3_Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
clss=LogisticRegression(random_state=0)
clss.fit(x_train,y_train)
y_pred=clss.predict(x_test)
print(accuracy_score(y_test,y_pred))


0.9801858536210737


In [13]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,median_absolute_error
print ("Mean absolute Error",mean_absolute_error(y_test,y_pred))
print ("Mean squared Error",mean_squared_error(y_test,y_pred))
print ("Median absolute Error",median_absolute_error(y_test,y_pred))

Mean absolute Error 0.01981414637892635
Mean squared Error 0.01981414637892635
Median absolute Error 0.0


In [14]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12763     0]
 [  258     0]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12763
           1       0.00      0.00      0.00       258

    accuracy                           0.98     13021
   macro avg       0.49      0.50      0.49     13021
weighted avg       0.96      0.98      0.97     13021



c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Makany\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



### 4_Naive_bayes

In [13]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes_model=MultinomialNB()
naive_bayes_model.fit(x_train, y_train)
y_pred=naive_bayes_model.predict(x_test)
print(accuracy_score(y_test, y_pred))


0.9801858536210737


In [14]:
print(confusion_matrix(y_test, y_pred))

[[12763     0]
 [  258     0]]


#### outliers

In [33]:
# Z score = (Observation — Mean)/Standard Deviation
# z = (X — μ) / σ
# dataset_test= [11,10,12,14,12,15,14,13,15,102,12,14,17,19,107, 10,13,12,14,12,108,12,11,14,13,15,10,15,12,10,14,13,15,10]


In [43]:
outliers=[]
def detect_outliers(data):
    
    threshold=2
    mean = np.mean(data)
    std =np.std(data)
    
    
    for i in data:
        z_score= (i - mean)/std 
        print(z_score)
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

In [44]:
outlier_pt=detect_outliers(x[:,7])

-0.21717646954826683
-0.38325839227030184
0.14862128482694098
-0.8221229143234996
1.317457609682155
2.469592959068114
-0.6237988306260978
3.225312099051898
-0.6219431666850695
2.35106242483493
-0.6356286882501535
-1.0995446735072338
1.35642655244375
-0.7186696496111709
-0.2190321334892951
-0.44333551236109353
-0.460732361808234
-0.5059641703707994
-1.0937457236915205
-0.8499578734389245
-0.6676388912328919
0.5812229410791683
-1.0267098638218721
2.174078476459354
0.123801779615687
-1.0123284682789027
-0.2290063271723225
-0.16220242529530302
2.3714747281862416
2.550778256488103
-0.5006291365403429
-0.02836266354863509
-1.129699212548944
-0.713102657788086
1.0500100441814482
-0.5136187841275413
-0.9715038615762795
-0.24106814278900648
-1.1380497002835714
-0.5173301120095978
0.3116877536448048
0.24024469191521441
-0.5871494677907885
0.1425903770185988
1.99987802399532
-0.5723041562625619
0.21217777480716088
0.8526137924545607
-1.1023281694187763
2.2861141868989385
-0.2361970249438073
-0.53

In [45]:
outlier_pt

[210.95,
 243.53,
 205.84,
 198.21,
 206.72,
 214.45,
 203.04,
 242.3,
 220.49,
 228.69,
 218.46,
 216.7,
 234.58,
 235.85,
 202.21,
 243.5,
 229.92,
 215.6,
 239.64,
 200.28,
 205.23,
 209.58,
 210.78,
 251.6,
 213.37,
 223.36,
 203.81,
 205.26,
 211.03,
 225.47,
 227.1,
 201.76,
 217.3,
 196.01,
 198.69,
 210.48,
 193.83,
 247.69,
 191.47,
 239.82,
 207.58,
 215.64,
 196.36,
 205.5,
 204.86,
 228.08,
 219.53,
 219.97,
 214.05,
 200.49,
 240.71,
 197.1,
 194.62,
 222.21,
 250.2,
 254.6,
 212.01,
 226.7,
 194.04,
 237.15,
 231.19,
 207.32,
 207.64,
 236.84,
 204.63,
 232.89,
 195.03,
 219.84,
 214.09,
 227.91,
 191.61,
 204.5,
 206.25,
 254.63,
 246.34,
 195.16,
 223.68,
 229.2,
 193.22,
 204.57,
 251.46,
 220.52,
 221.29,
 195.04,
 218.65,
 211.49,
 224.71,
 226.11,
 210.94,
 230.68,
 198.02,
 204.17,
 267.76,
 217.71,
 239.52,
 229.86,
 210.96,
 195.25,
 217.39,
 201.25,
 197.79,
 214.77,
 206.4,
 197.58,
 199.96,
 217.08,
 205.77,
 237.21,
 246.53,
 193.94,
 206.33,
 206.98,
 227.28